import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Download, FileSpreadsheet, Filter, Plus, Search, Users } from 'lucide-react';
import { useFinanceStore } from '@/store/finance-store';
import { useStudentStore } from '@/store/student-store';
import { getStudentFeeSummary, getStudentPreviousPending, groupRosterByClass, summarizeRoster } from '@/lib/student-fees';
import { MEDIUM_LABELS, type StudentMedium } from '@/types/students';
import { formatINR } from '@/utils/currency';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { AddStudentModal } from '@/components/AddStudentModal';
import { StudentImportWizard } from '@/components/StudentImportWizard';
import { downloadStudentImportTemplate } from '@/lib/student-import';

type FeeFilter = 'all' | 'paid' | 'partial' | 'unpaid' | 'previous';

export default function StudentsPage() {
  const { academicYears, currentYearId, incomeEntries } = useFinanceStore(); const { students, enrollments } = useStudentStore(); const navigate = useNavigate();
  const [yearId, setYearId] = useState(currentYearId); const [query, setQuery] = useState(''); const [classFilter, setClassFilter] = useState('all'); const [medium, setMedium] = useState<'all' | StudentMedium>('all'); const [feeFilter, setFeeFilter] = useState<FeeFilter>('all'); const [showAdd, setShowAdd] = useState(false); const [showImport, setShowImport] = useState(false);
  const year = academicYears.find((item) => item.id === yearId); const roster = enrollments.filter((item) => item.academicYearId === yearId && item.status === 'active');
  const summary = useMemo(() => summarizeRoster(roster, incomeEntries), [roster, incomeEntries]);
  const classes = useMemo(() => groupRosterByClass(roster, incomeEntries), [roster, incomeEntries]);
  const rows = useMemo(() => roster.map((enrollment) => {
    const student = students.find((item) => item.id === enrollment.studentId); const fees = getStudentFeeSummary(enrollment, incomeEntries); const previous = getStudentPreviousPending(enrollment.studentId, yearId, enrollments, incomeEntries); return { student, enrollment, fees, previous };
  }).filter((row) => row.student).filter((row) => { const q = query.trim().toLowerCase(); if (q && !row.student!.fullName.toLowerCase().includes(q) && !row.student!.admissionNumber.toLowerCase().includes(q)) return false; if (classFilter !== 'all' && row.enrollment.className !== classFilter) return false; if (medium !== 'all' && row.enrollment.medium !== medium) return false; if (feeFilter === 'paid' && row.fees.status !== 'paid') return false; if (feeFilter === 'partial' && row.fees.status !== 'partially_paid') return false; if (feeFilter === 'unpaid' && row.fees.status !== 'not_paid') return false; if (feeFilter === 'previous' && row.previous <= 0) return false; return true; }), [roster, students, incomeEntries, yearId, enrollments, query, classFilter, medium, feeFilter]);
  const linkedCurrent = incomeEntries.filter((entry) => entry.studentEnrollmentId && roster.some((item) => item.id === entry.studentEnrollmentId)).reduce((sum, entry) => sum + entry.amount, 0);
  const globalCurrent = incomeEntries.filter((entry) => entry.category === 'Tuition Fees' && !entry.isLateCollection && entry.academicYearId === yearId).reduce((sum, entry) => sum + entry.amount, 0);
  return <div className="space-y-6 animate-fade-in"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-primary">School</p><h1 className="text-2xl font-bold">Students</h1><p className="text-sm text-muted-foreground">Roster and student fee accounts</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={downloadStudentImportTemplate}><Download className="mr-2 h-4 w-4" />Template</Button><Button variant="outline" onClick={() => setShowImport(true)}><FileSpreadsheet className="mr-2 h-4 w-4" />Import</Button><Button onClick={() => setShowAdd(true)}><Plus className="mr-2 h-4 w-4" />Add Student</Button></div></div>
    <div className="max-w-xs"><Select value={yearId} onValueChange={setYearId}><SelectTrigger aria-label="Academic year"><SelectValue /></SelectTrigger><SelectContent>{academicYears.map((item) => <SelectItem key={item.id} value={item.id}>Academic Year {item.label}</SelectItem>)}</SelectContent></Select></div>
    <section className="rounded-xl border bg-card p-4 sm:p-5"><div className="mb-4"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-primary">School Strength</p><h2 className="text-lg font-semibold">AY {year?.label || '—'}</h2></div><div className="grid grid-cols-2 gap-4 lg:grid-cols-5"><Metric label="Total Students" value={summary.totalStudents} prominent /><Metric label="English Medium" value={summary.english} /><Metric label="Gujarati Medium" value={summary.gujarati} /><Metric label="Fees Pending" value={summary.pendingStudents} tone="warning" /><Metric label="Fully Paid" value={summary.fullyPaidStudents} tone="income" /></div></section>
    <section className="rounded-xl border bg-card"><div className="border-b p-4"><h2 className="font-semibold">Class Strength & Fees</h2><p className="text-xs text-muted-foreground">Active students in this academic year</p></div>{classes.length ? <><div className="hidden overflow-auto md:block"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-muted-foreground"><th className="p-3">Class</th><th>English</th><th>Gujarati</th><th>Total</th><th>Current Fees</th><th>Collected</th><th>Pending</th></tr></thead><tbody>{classes.map((item) => <tr key={item.className} className="border-b last:border-0"><td className="p-3 font-medium">{item.className}</td><td>{item.english}</td><td>{item.gujarati}</td><td>{item.totalStudents}</td><td>{formatINR(item.obligation)}</td><td className="text-income">{formatINR(item.collected)}</td><td className="text-warning">{formatINR(item.pending)}</td></tr>)}</tbody></table></div><div className="divide-y md:hidden">{classes.map((item) => <div key={item.className} className="p-4"><div className="flex justify-between"><span className="font-semibold">{item.className}</span><span>{item.totalStudents} students</span></div><p className="mt-1 text-xs text-muted-foreground">English {item.english} · Gujarati {item.gujarati}</p><div className="mt-3 grid grid-cols-2 gap-2 text-xs"><span>Collected <strong className="block text-income">{formatINR(item.collected)}</strong></span><span>Pending <strong className="block text-warning">{formatINR(item.pending)}</strong></span></div></div>)}</div></> : <p className="p-8 text-center text-sm text-muted-foreground">No students added for AY {year?.label}. Import your roster or add one student manually.</p>}</section>
    <section className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Roster Reconciliation</h2><p className="mb-4 text-xs text-muted-foreground">Student subledger compared with the existing aggregate finance ledger</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Money label="Academic-Year Tuition Target" value={year?.targetTuitionFees || 0}/><Money label="Student Roster Fee Total" value={summary.obligation}/><Money label="Target Difference" value={(year?.targetTuitionFees || 0) - summary.obligation} tone="warning"/><Money label="Unassigned Tuition Received" value={globalCurrent - linkedCurrent} tone="warning"/></div></section>
    <section className="space-y-3"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" placeholder="Search students or admission number..." value={query} onChange={(e) => setQuery(e.target.value)}/></div><div className="grid grid-cols-2 gap-2 lg:grid-cols-4"><Select value={classFilter} onValueChange={setClassFilter}><SelectTrigger><SelectValue placeholder="Class"/></SelectTrigger><SelectContent><SelectItem value="all">All Classes</SelectItem>{classes.map((item) => <SelectItem key={item.className} value={item.className}>{item.className}</SelectItem>)}</SelectContent></Select><Select value={medium} onValueChange={(value) => setMedium(value as 'all' | StudentMedium)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All Mediums</SelectItem><SelectItem value="english">English</SelectItem><SelectItem value="gujarati">Gujarati</SelectItem></SelectContent></Select><Select value={feeFilter} onValueChange={(value) => setFeeFilter(value as FeeFilter)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All Fee Statuses</SelectItem><SelectItem value="paid">Fully Paid</SelectItem><SelectItem value="partial">Partially Paid</SelectItem><SelectItem value="unpaid">Not Paid</SelectItem><SelectItem value="previous">Previous-Year Dues</SelectItem></SelectContent></Select><Button variant="outline" onClick={() => { setQuery(''); setClassFilter('all'); setMedium('all'); setFeeFilter('all'); }}><Filter className="mr-2 h-4 w-4"/>Clear Filters</Button></div>
      {rows.length ? <div className="grid gap-3 lg:grid-cols-2">{rows.map(({ student, enrollment, fees, previous }) => <button type="button" key={enrollment.id} onClick={() => navigate(`/students/${student!.id}`)} className="rounded-lg border bg-card p-4 text-left transition hover:border-primary/40 hover:shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate font-semibold">{student!.fullName}</p><p className="text-xs text-muted-foreground">{student!.admissionNumber || 'No admission number'} · {enrollment.className} · {MEDIUM_LABELS[enrollment.medium]}</p></div><FeeBadge status={fees.status}/></div><div className="mt-4 grid grid-cols-3 gap-2 text-xs"><span>Fee<strong className="money-fit block font-mono text-sm">{formatINR(fees.obligation)}</strong></span><span>Paid<strong className="money-fit block font-mono text-sm text-income">{formatINR(fees.collected)}</strong></span><span>Pending<strong className="money-fit block font-mono text-sm text-warning">{formatINR(fees.pending)}</strong></span></div>{previous > 0 && <p className="mt-3 border-t pt-2 text-xs font-medium text-warning">Previous-year pending: {formatINR(previous)}</p>}</button>)}</div> : <div className="rounded-xl border border-dashed p-10 text-center"><Users className="mx-auto mb-3 h-10 w-10 text-muted-foreground/30"/><p className="font-medium">No students match these filters</p></div>}
    </section><AddStudentModal open={showAdd} onClose={() => setShowAdd(false)} defaultYearId={yearId}/><StudentImportWizard open={showImport} onClose={() => setShowImport(false)} defaultYearId={yearId}/></div>;
}

function Metric({ label, value, prominent, tone }: { label: string; value: number; prominent?: boolean; tone?: 'warning' | 'income' }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className={`${prominent ? 'text-3xl' : 'text-2xl'} font-bold ${tone === 'warning' ? 'text-warning' : tone === 'income' ? 'text-income' : ''}`}>{value}</p></div>; }
function Money({ label, value, tone }: { label: string; value: number; tone?: 'warning' }) { return <div className="rounded-lg bg-muted/40 p-3"><p className="text-xs text-muted-foreground">{label}</p><p className={`money-fit mt-1 font-mono font-semibold ${tone ? 'text-warning' : ''}`}>{formatINR(value)}</p></div>; }
function FeeBadge({ status }: { status: 'not_paid' | 'partially_paid' | 'paid' }) { return <Badge variant="outline" className={status === 'paid' ? 'border-income/30 text-income' : status === 'partially_paid' ? 'border-warning/30 text-warning' : 'border-destructive/30 text-destructive'}>{status === 'paid' ? 'Paid' : status === 'partially_paid' ? 'Partially Paid' : 'Not Paid'}</Badge>; }
