import { useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, Archive, Edit, IndianRupee } from 'lucide-react';
import { useStudentStore } from '@/store/student-store'; import { useFinanceStore } from '@/store/finance-store';
import { getStudentFeeSummary } from '@/lib/student-fees'; import { MEDIUM_LABELS } from '@/types/students'; import { formatINR } from '@/utils/currency';
import { Button } from '@/components/ui/button'; import { Badge } from '@/components/ui/badge'; import { Progress } from '@/components/ui/progress';
import { AddIncomeModal } from '@/components/AddIncomeModal'; import { AddStudentModal } from '@/components/AddStudentModal'; import { toast } from '@/hooks/use-toast';

export default function StudentDetailPage() {
  const { studentId } = useParams(); const navigate = useNavigate(); const { students, enrollments, archiveStudent } = useStudentStore(); const { currentYearId, academicYears, incomeEntries, accounts } = useFinanceStore();
  const student = students.find((item) => item.id === studentId); const studentEnrollments = enrollments.filter((item) => item.studentId === studentId).sort((a,b) => (academicYears.find((y) => y.id === b.academicYearId)?.startDate.getTime() || 0) - (academicYears.find((y) => y.id === a.academicYearId)?.startDate.getTime() || 0)); const current = studentEnrollments.find((item) => item.academicYearId === currentYearId) || studentEnrollments[0];
  const [paymentEnrollmentId, setPaymentEnrollmentId] = useState<string>(); const [editing, setEditing] = useState(false);
  const [addingHistorical, setAddingHistorical] = useState(false);
  const payments = useMemo(() => incomeEntries.filter((entry) => studentEnrollments.some((enrollment) => enrollment.id === entry.studentEnrollmentId)).sort((a,b) => b.date.getTime()-a.date.getTime()), [incomeEntries, studentEnrollments]);
  if (!student || !current) return <div className="py-16 text-center"><p>Student not found.</p><Button variant="link" onClick={() => navigate('/students')}>Back to Students</Button></div>;
  const currentSummary = getStudentFeeSummary(current, incomeEntries); const currentYear = academicYears.find((item) => item.id === current.academicYearId); const previous = studentEnrollments.filter((item) => item.id !== current.id).map((enrollment) => ({ enrollment, year: academicYears.find((item) => item.id === enrollment.academicYearId), summary: getStudentFeeSummary(enrollment, incomeEntries) }));
  async function archive() { if (!confirm(`Archive ${student.fullName}? Historical fee and payment records will remain available.`)) return; try { await archiveStudent(student.id); toast({ title: 'Student archived' }); } catch (error) { toast({ title: 'Archive failed', description: error instanceof Error ? error.message : 'Database error', variant: 'destructive' }); } }
  return <div className="space-y-6 animate-fade-in"><Link to="/students" className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4"/>Students</Link><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-bold">{student.fullName}</h1><Badge variant={student.status === 'active' ? 'default' : 'secondary'}>{student.status}</Badge></div><p className="text-sm text-muted-foreground">{student.admissionNumber ? `Admission ${student.admissionNumber} · ` : ''}{current.className} · {MEDIUM_LABELS[current.medium]} Medium</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setEditing(true)}><Edit className="mr-2 h-4 w-4"/>Edit</Button><Button onClick={() => setPaymentEnrollmentId(current.id)}><IndianRupee className="mr-2 h-4 w-4"/>Record Fee Payment</Button><Button variant="ghost" onClick={archive} aria-label="Archive student"><Archive className="h-4 w-4"/></Button></div></div>
    <section className="rounded-xl border bg-card p-4 sm:p-5"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-primary">Current-Year Fees</p><h2 className="font-semibold">AY {currentYear?.label}</h2></div><span className="text-sm font-semibold">{Math.round(currentSummary.collectionPercent)}%</span></div><div className="grid grid-cols-3 gap-3"><FeeMetric label="Total" value={currentSummary.obligation}/><FeeMetric label="Collected" value={currentSummary.collected} tone="income"/><FeeMetric label="Pending" value={currentSummary.pending} tone="warning"/></div><Progress value={currentSummary.collectionPercent} className="my-4 h-2.5"/><div className="grid grid-cols-2 gap-2 border-t pt-4 sm:grid-cols-4"><Small label="Cash" value={currentSummary.cash}/><Small label="UPI" value={currentSummary.upi}/><Small label="Other" value={currentSummary.other}/><Small label="Opening Imported" value={currentSummary.openingCollected}/></div>{currentSummary.openingCollected > 0 && <p className="mt-3 text-xs text-muted-foreground">Opening imported history is part of this student balance but did not create finance income.</p>}</section>
    <section className="rounded-xl border bg-card"><div className="flex items-center justify-between gap-3 border-b p-4"><h2 className="font-semibold">Previous-Year Fees</h2><Button size="sm" variant="outline" onClick={() => setAddingHistorical(true)}>Add Historical Fee</Button></div>{previous.length ? <div className="divide-y">{previous.map(({ enrollment, year, summary }) => <div key={enrollment.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center"><div className="flex-1"><p className="font-medium">AY {year?.label || '—'} · {enrollment.className}</p><p className="text-xs text-muted-foreground">Obligation {formatINR(summary.obligation)} · Collected {formatINR(summary.collected)}</p></div><span className={`font-mono font-semibold ${summary.pending > 0 ? 'text-warning' : 'text-income'}`}>{summary.pending > 0 ? `${formatINR(summary.pending)} pending` : 'Fully paid'}</span>{summary.pending > 0 && <Button size="sm" variant="outline" onClick={() => setPaymentEnrollmentId(enrollment.id)}>Record Payment</Button>}</div>)}</div> : <p className="p-5 text-sm text-muted-foreground">No previous-year fee balance is currently recorded for this student.</p>}</section>
    <section className="rounded-xl border bg-card"><div className="border-b p-4"><h2 className="font-semibold">Payment History</h2></div>{currentSummary.openingCollected > 0 && <div className="border-b bg-muted/20 p-4"><p className="text-sm font-medium">Opening imported fee history · {formatINR(currentSummary.openingCollected)}</p><p className="text-xs text-muted-foreground">Cash {formatINR(current.openingCollectedCash)} · UPI {formatINR(current.openingCollectedUpi)} · Other {formatINR(current.openingCollectedOther)}</p></div>}{payments.length ? <div className="divide-y">{payments.map((entry) => { const enrollment = studentEnrollments.find((item) => item.id === entry.studentEnrollmentId); const year = academicYears.find((item) => item.id === enrollment?.academicYearId); return <div key={entry.id} className="flex items-start gap-3 p-4"><div className="min-w-0 flex-1"><p className="text-sm font-medium">{entry.date.toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})} · {entry.isLateCollection ? `Previous-Year Fee for AY ${year?.label}` : 'Current-Year Fee'}</p><p className="text-xs text-muted-foreground">{entry.paymentMethod?.replace('_',' ') || 'Unknown / Not Recorded'} · {accounts.find((item) => item.id === entry.accountId)?.name || 'Unknown account'}{entry.paymentReference ? ` · ${entry.paymentReference}` : ''}</p></div><span className="money-fit font-mono font-semibold text-income">{formatINR(entry.amount)}</span></div>; })}</div> : <p className="p-5 text-sm text-muted-foreground">No payments recorded in the application yet.</p>}</section>
    <AddIncomeModal isOpen={!!paymentEnrollmentId} onClose={() => setPaymentEnrollmentId(undefined)} presetStudentEnrollmentId={paymentEnrollmentId}/><AddStudentModal open={editing} onClose={() => setEditing(false)} student={student} enrollment={current}/><AddStudentModal open={addingHistorical} onClose={() => setAddingHistorical(false)} student={student} defaultYearId={academicYears.find((year) => year.id !== current.academicYearId)?.id}/></div>;
}
function FeeMetric({ label,value,tone }: {label:string;value:number;tone?:'income'|'warning'}) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className={`money-fit font-mono text-lg font-bold ${tone==='income'?'text-income':tone==='warning'?'text-warning':''}`}>{formatINR(value)}</p></div>; }
function Small({label,value}:{label:string;value:number}) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="money-fit font-mono text-sm font-semibold">{formatINR(value)}</p></div>; }
