import { useEffect, useMemo, useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Download, FileSpreadsheet, Loader2, Upload } from 'lucide-react';
import { useFinanceStore } from '@/store/finance-store';
import { useStudentStore } from '@/store/student-store';
import { downloadStudentImportTemplate, IMPORT_FIELDS, parseStudentWorkbook, suggestMapping, validateImportRows, type ColumnMapping, type ParsedSheet } from '@/lib/student-import';
import { formatINR } from '@/utils/currency';
import { toast } from '@/hooks/use-toast';

type Step = 'upload' | 'map' | 'preview' | 'result';

export function StudentImportWizard({ open, onClose, defaultYearId }: { open: boolean; onClose: () => void; defaultYearId: string }) {
  const { academicYears } = useFinanceStore(); const { students, enrollments, importRoster } = useStudentStore();
  const [step, setStep] = useState<Step>('upload'); const [yearId, setYearId] = useState(defaultYearId);
  const [sheets, setSheets] = useState<ParsedSheet[]>([]); const [sheetIndex, setSheetIndex] = useState(0); const [mapping, setMapping] = useState<ColumnMapping>({});
  const [snapshotDate, setSnapshotDate] = useState(new Date().toISOString().slice(0, 10)); const [busy, setBusy] = useState(false);
  const [result, setResult] = useState<{ added: number; updated: number; failed: number; total: number }>();
  useEffect(() => { if (open && step === 'upload') setYearId(defaultYearId); }, [defaultYearId, open, step]);
  const sheet = sheets[sheetIndex];
  const preview = useMemo(() => { if (!sheet || step === 'upload') return []; try { return validateImportRows(sheet.rows, mapping, students, enrollments, yearId, academicYears, snapshotDate); } catch { return []; } }, [sheet, step, mapping, students, enrollments, yearId, academicYears, snapshotDate]);
  const valid = preview.filter((row) => row.errors.length === 0); const invalid = preview.filter((row) => row.errors.length > 0);
  function reset() { setStep('upload'); setSheets([]); setSheetIndex(0); setMapping({}); setResult(undefined); setYearId(defaultYearId); }
  async function chooseFile(file?: File) { if (!file) return; setBusy(true); try { const parsed = await parseStudentWorkbook(file); if (!parsed.length || parsed.every((item) => !item.rows.length)) throw new Error('No student rows were found'); setSheets(parsed); setSheetIndex(0); setMapping(suggestMapping(parsed[0].headers)); setStep('map'); } catch (error) { toast({ title: 'File could not be read', description: error instanceof Error ? error.message : 'Invalid spreadsheet', variant: 'destructive' }); } finally { setBusy(false); } }
  function continueToPreview() { try { validateImportRows(sheet.rows, mapping, students, enrollments, yearId, academicYears, snapshotDate); setStep('preview'); } catch (error) { toast({ title: 'Column mapping is incomplete', description: error instanceof Error ? error.message : 'Review the mapping', variant: 'destructive' }); } }
  async function confirmImport() { if (!valid.length || invalid.length) return; setBusy(true); try { const value = await importRoster(yearId, valid); setResult(value); setStep('result'); } catch (error) { toast({ title: 'Import failed safely', description: error instanceof Error ? error.message : 'No rows were committed', variant: 'destructive' }); } finally { setBusy(false); } }
  return <Dialog open={open} onOpenChange={(value) => { if (!value) { reset(); onClose(); } }}><DialogContent className="max-h-[92vh] overflow-y-auto sm:max-w-4xl"><DialogHeader><DialogTitle>Import Student Roster</DialogTitle></DialogHeader>
    {step === 'upload' && <div className="space-y-4"><div><Label>Academic Year</Label><Select value={yearId} onValueChange={setYearId}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{academicYears.map((year) => <SelectItem key={year.id} value={year.id}>AY {year.label}</SelectItem>)}</SelectContent></Select></div><div className="rounded-xl border-2 border-dashed p-8 text-center"><FileSpreadsheet className="mx-auto mb-3 h-10 w-10 text-primary" /><p className="font-medium">Choose an Excel or CSV roster</p><p className="mb-4 text-sm text-muted-foreground">.xlsx, .xls, or .csv · up to 10 MB and 5,000 rows</p><Input type="file" accept=".xlsx,.xls,.csv" className="mx-auto max-w-sm" onChange={(event) => void chooseFile(event.target.files?.[0])} disabled={busy} />{busy && <Loader2 className="mx-auto mt-3 h-5 w-5 animate-spin" />}</div><Button type="button" variant="outline" onClick={downloadStudentImportTemplate}><Download className="mr-2 h-4 w-4" />Download Import Template</Button></div>}
    {step === 'map' && sheet && <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><div><Label>Sheet</Label><Select value={String(sheetIndex)} onValueChange={(value) => { const next = Number(value); setSheetIndex(next); setMapping(suggestMapping(sheets[next].headers)); }}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{sheets.map((item, index) => <SelectItem key={item.name} value={String(index)}>{item.name} ({item.rows.length} rows)</SelectItem>)}</SelectContent></Select></div><div><Label>Opening Snapshot Date</Label><Input type="date" value={snapshotDate} onChange={(e) => setSnapshotDate(e.target.value)} /></div></div><div className="rounded-lg border"><div className="grid grid-cols-2 border-b bg-muted/50 px-3 py-2 text-xs font-semibold"><span>Your Column</span><span>Import As</span></div>{sheet.headers.map((header, index) => <div key={`${header}-${index}`} className="grid grid-cols-2 items-center gap-3 border-b px-3 py-2 last:border-0"><span className="truncate text-sm">{header || `Column ${index + 1}`}</span><Select value={mapping[index] || 'ignore'} onValueChange={(value) => setMapping((current) => ({ ...current, [index]: value as ColumnMapping[number] }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{IMPORT_FIELDS.map((field) => <SelectItem key={field.value} value={field.value}>{field.label}</SelectItem>)}</SelectContent></Select></div>)}</div><div className="flex justify-between"><Button variant="outline" onClick={() => setStep('upload')}>Back</Button><Button onClick={continueToPreview}>Validate & Preview</Button></div></div>}
    {step === 'preview' && <div className="space-y-4"><Alert><AlertTitle>Opening collections do not create income</AlertTitle><AlertDescription>These values only establish each student's fee history. Account balances and the finance ledger are unchanged.</AlertDescription></Alert><div className="flex flex-wrap gap-3 text-sm"><span className="rounded-full bg-primary/10 px-3 py-1">{valid.length} ready</span><span className="rounded-full bg-destructive/10 px-3 py-1 text-destructive">{invalid.length} blocked</span><span className="rounded-full bg-muted px-3 py-1">{preview.filter((row) => row.action === 'update').length} updates</span></div><div className="max-h-[48vh] overflow-auto rounded-lg border"><table className="w-full min-w-[760px] text-sm"><thead className="sticky top-0 bg-card"><tr className="border-b text-left text-xs text-muted-foreground"><th className="p-2">Row</th><th>Name</th><th>Class / Medium</th><th>Fee</th><th>Opening Paid</th><th>Action</th><th>Validation</th></tr></thead><tbody>{preview.map((row) => <tr key={row.rowNumber} className="border-b align-top"><td className="p-2">{row.rowNumber}</td><td><span className="font-medium">{row.fullName || '—'}</span><br/><span className="text-xs text-muted-foreground">{row.admissionNumber || 'No admission no.'}</span></td><td>{row.className} · {row.medium || 'Invalid'}</td><td>{row.annualFeeAmount === null ? 'Invalid' : formatINR(row.annualFeeAmount + row.additionalOutstandingAmount)}</td><td>{formatINR(row.openingCollectedCash + row.openingCollectedUpi + row.openingCollectedOther)}{row.inferredOpening && <span className="block text-xs text-warning">Inferred</span>}</td><td className="capitalize">{row.action.replace('_',' ')}</td><td className="max-w-xs p-2 text-xs">{row.errors.map((error) => <p key={error} className="text-destructive">{error}</p>)}{row.warnings.map((warning) => <p key={warning} className="text-warning">{warning}</p>)}</td></tr>)}</tbody></table></div>{invalid.length > 0 && <p className="text-sm text-destructive">Resolve all blocked rows in the source file before importing. No partial import will run.</p>}<div className="flex justify-between"><Button variant="outline" onClick={() => setStep('map')}>Back</Button><Button onClick={confirmImport} disabled={busy || valid.length === 0 || invalid.length > 0}>{busy ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Upload className="mr-2 h-4 w-4" />}Confirm Import</Button></div></div>}
    {step === 'result' && result && <div className="space-y-5 py-4 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-income/10"><FileSpreadsheet className="h-7 w-7 text-income" /></div><div><h3 className="text-xl font-semibold">{result.total} students imported</h3><p className="text-sm text-muted-foreground">{result.added} added · {result.updated} updated · {result.failed} failed</p></div><Button onClick={() => { reset(); onClose(); }}>Done</Button></div>}
  </DialogContent></Dialog>;
}
