// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvxdsryxxcvrqxpdqxwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12eGRzcnl4eGN2cnF4cGRxeHd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQxMDAzNDEsImV4cCI6MjA4OTY3NjM0MX0.tOc2TaWT-XQ9OZglvfG2A803jhZF9gL6jKoGyDZW6-4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});